services:
  shared:
    image: busybox
    container_name: shared
    command: sh -c "while true; do sleep 3600; done"
    stdin_open: true
    tty: true
    ipc: shareable

  accessor:
    image: busybox
    command: sh -c "while true; do sleep 3600; done"
    stdin_open: true
    tty: true
    # ipc: "container:shared"
    ipc: "service:shared"
    depends_on:
      - shared
