services:
  shared:
    image: busybox
    container_name: shared
    command: sh -c "while true; do sleep 3600; done"
    stdin_open: true
    tty: true
    pid: "host"

  accessor:
    image: busybox
    command: sh -c "while true; do sleep 4800; done"
    stdin_open: true
    tty: true
    pid: "host"
    depends_on:
      - shared
