services:
  agent:
    image: busybox
    user: "1000:1000"
    command: sh -c "while true; do sleep 3600; done"
    volumes:
      - log:/var/log/selenium

  node:
    image: busybox
    user: "1000:1000"
    command: sh -c "while true; do sleep 3600; done"
    volumes:
      - log:/var/log/selenium

  initializer:
    image: busybox
    command: |
      touch /var/log/selenium/selenium1.log;
      chown -R 1000:1000 /var/log/selenium;
      chmod -R 775 /var/log/selenium;
    volumes:
      - log:/var/log/selenium


volumes:
  log:
