services:
  agent:
    image: busybox
    user: "1000:1000"
    command: sh -c "while true; do sleep 3600; done"
    volumes:
      - log:/var/log/selenium

  node:
    image: busybox
    user: "1000:1000"
    # Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./scripts/node-entrypoint.sh": permission denied: unknown
    # entrypoint: ["./scripts/node-entrypoint.sh"] # Does not work
    command: sh -c "while true; do sleep 3600; done"
    volumes:
      - log:/var/log/selenium
      # - ./scripts/node-entrypoint.sh:/scripts/node-entrypoint.sh # Does not work

  initializer:
    image: busybox
    command: |
      touch /var/log/selenium/selenium1.log;
      chown -R 1000:1000 /var/log/selenium;
      chmod -R 775 /var/log/selenium;
    volumes:
      - log:/var/log/selenium


volumes:
  log:
