services:
  agent:
    image: busybox
    command: sh -c "while true; do sleep 3600; done"
    volumes:
      - log:/var/log/selenium

  node:
    image: busybox
    command: sh -c "while true; do sleep 3600; done"
    volumes:
      - log:/var/log/selenium

volumes:
  log:
